version: 0.9.{build}

environment:
  matrix:
    - QTDIR: C:\Qt\5.6\msvc2013
      cname: Win32-VS2013
      VSVER: 12.0
      PT: v120
    - QTDIR: C:\Qt\5.3\mingw482_32
      cname: mingw
    - QTDIR: C:\Qt\5.6\msvc2013_64
      cname: Win64-VS2013
      VSVER: 12.0
      PT: v120
    - QTDIR: C:\Qt\5.6\msvc2015_64
      cname: Win64-VS2015
      VSVER: 14.0
      PT: v140
    - QTDIR: C:\Qt\5.6\msvc2015
      cname: Win32-VS2015
      VSVER: 14.0
      PT: v140
    - QTDIR: C:\Qt\5.6\mingw49_32
      cname: mingw

configuration:
  - release

install:
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %cname%==mingw set make=mingw32-make.exe
  - if %cname%==mingw g++ --version
  - if %cname%==mingw %make% --version
  - if not %cname%==mingw call "%ProgramFiles(x86)%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" %ARCH%
  - if not %cname%==mingw set make=nmake.exe
  - if not %cname%==mingw %make% /? > nul

before_build:
  - if %cname%==mingw set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\shared
  - cd %APPVEYOR_BUILD_FOLDER%\pointing
  - qmake -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\pointing
  - '%make%'
  # Also, build vcxproj (without qt)
  - if not %cname%==mingw msbuild /m /p:Configuration=%CONFIGURATION% /p:Platform=%ARCH% pointing.vcxproj /p:PlatformToolset=%PT% /t:Rebuild

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\tests
  - qmake -Wall -Wlogic -Wparser CONFIG+=%CONFIGURATION%
  - '%make% check -s'

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - 7z a libpointing-%APPVEYOR_REPO_TAG_NAME%-%cname%.zip pointing-echomouse\*
  - 7z a libpointing-%APPVEYOR_REPO_TAG_NAME%-%cname%.zip pointing\*.h
  - 7z a libpointing-%APPVEYOR_REPO_TAG_NAME%-%cname%.zip pointing\**\*.h
  - 7z a libpointing-%APPVEYOR_REPO_TAG_NAME%-%cname%.zip pointing\input\windows\*.h
  - 7z a libpointing-%APPVEYOR_REPO_TAG_NAME%-%cname%.zip pointing\output\windows\*.h
  - 7z a libpointing-%APPVEYOR_REPO_TAG_NAME%-%cname%.zip pointing\transferfunctions\windows\*.h
  - 7z a libpointing-%APPVEYOR_REPO_TAG_NAME%-%cname%.zip pointing\utils\windows\*.h
  - 7z a libpointing-%APPVEYOR_REPO_TAG_NAME%-%cname%.zip pointing-xorg\**\*.h
  - if %cname%==mingw 7z a libpointing-%APPVEYOR_REPO_TAG_NAME%-%cname%.zip %APPVEYOR_BUILD_FOLDER%\pointing\%CONFIGURATION%\libpointing.a
  - if %cname%==Win64-VS2013 7z a libpointing-%APPVEYOR_REPO_TAG_NAME%-%cname%.zip %APPVEYOR_BUILD_FOLDER%\pointing\%ARCH%\%CONFIGURATION%\pointing.lib
  - if %cname%==Win64-VS2015 7z a libpointing-%APPVEYOR_REPO_TAG_NAME%-%cname%.zip %APPVEYOR_BUILD_FOLDER%\pointing\%ARCH%\%CONFIGURATION%\pointing.lib
  - if %cname%==Win32-VS2013 7z a libpointing-%APPVEYOR_REPO_TAG_NAME%-%cname%.zip %APPVEYOR_BUILD_FOLDER%\pointing\%CONFIGURATION%\pointing.lib
  - if %cname%==Win32-VS2015 7z a libpointing-%APPVEYOR_REPO_TAG_NAME%-%cname%.zip %APPVEYOR_BUILD_FOLDER%\pointing\%CONFIGURATION%\pointing.lib

artifacts:
  - path: '*.zip'
    name: libpointing-archive

deploy:
    provider: GitHub
    description: 'New release of libpointing'
    auth_token:
      secure: 1UNYGNi45HjR94wYYU6mMM1n9M2VE0gIVcyEjjJgixN1zkWxd16B/Bwz6PDksRv3
    on:
      appveyor_repo_tag: true

notifications:
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false